# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('price', models.FloatField()),
                ('uses', models.IntegerField(default=1)),
                ('times_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('spex', models.BooleanField()),
                ('nachspex', models.BooleanField()),
                ('diet', models.CharField(default='', max_length=128)),
                ('alcoholfree', models.BooleanField()),
                ('avec', models.CharField(default='', max_length=256)),
                ('comment', models.TextField(default='none')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(blank=True, db_column='participants', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.DiscountCode')),
            ],
        ),
    ]
